### ISSUE TITLE
ABPresence uses API that’s deprecated on OS X 10.9

### ISSUE THREAD

**Issue by alloy** [HipByte/RubyMotionSamples#34]
```
2013-11-04 18:46:48.452 ABPresence[20451:303] service_watcher.rb:9:in `startMonitoring': undefined method `addObserver' for nil:NilClass (NoMethodError)
from people_controller.rb:39:in `initialize:'
from app_delegate.rb:13:in `buildWindow'
from app_delegate.rb:4:in `applicationDidFinishLaunching:'
2013-11-04 18:46:48.453 ABPresence[20451:303] *nil description*
```

Might work if the deployment target is set to < 10.9, otherwise it should be updated.

**Comment by Watson1978** [comment]
RubyMotion dropped OS X 10.8 or below. So, I just removed sample.
