### ISSUE TITLE
Android example error

### ISSUE THREAD

**Issue by ruanwz** [HipByte/RubyMotionSamples#52]
For the example States and Conference, rake device command failed.

```
/AndroidRuntime(  306): android.content.res.Resources$NotFoundException: Resource ID #0x0
E/AndroidRuntime(  306): 	at android.content.res.Resources.getValue(Resources.java:1123)
E/AndroidRuntime(  306): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2312)
E/AndroidRuntime(  306): 	at android.content.res.Resources.getLayout(Resources.java:939)
E/AndroidRuntime(  306): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
```

Is it because some resource files are not included in the example, like the following lines:

```ruby
Android::Widget::ArrayAdapter.new(self, Android::R::Layout::Simple_list_item_1, States.all)

```

**Comment by ruanwz** [comment]
After updated to rubymotion 3.6 and android 5.02. Now 2 demos are working now.
